version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      SERVER_PORT: 8080
      CASSANDRA_CONTACT-POINTS: cassandra
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"


  cassandra:
    image: cassandra:4.0.4
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - cassandra_config:/etc/cassandra
      - ./cassandra_config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      CASSANDRA_CLUSTER_NAME: BooksCluster

volumes:
  cassandra_data:
  cassandra_config:
